const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const shared=fs.readFileSync('shared-results.js','utf8'),feed=JSON.parse(fs.readFileSync('official-results.json','utf8'));
function tab(storage=new Map(),fetcher){const timers=[];const ctx={localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},J3OfficialApi:{baseUrl:'https://j3-official-refresh.hideakiito382.chatgpt.site'},fetch:fetcher,AbortController,setTimeout:(f,ms)=>{timers.push({f,ms});return timers.length},clearTimeout(){},console};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(shared,ctx);return {api:ctx.J3Results,ctx,storage,timers};}
const reply=(t,f=feed)=>({ok:true,status:200,json:async()=>({status:'unchanged',feed:{...f,officialCheckedAt:new Date().toISOString()},resultId:t.api.resultId(f.matches.map(r=>r.game))})});
test('reload without network retains last good complete feed and never claims fresh verification',async()=>{const t=tab();t.api.applyOfficialFeed(feed);const reloaded=tab(t.storage,async()=>{throw Error('offline')});assert.equal(reloaded.api.initialGames.length,feed.matches.length);assert.equal(reloaded.api.feedState.state,'cached');assert.equal(reloaded.api.verification(reloaded.api.clubStats().stats).ok,false);await reloaded.api.refreshOfficial(true);assert.equal(reloaded.api.initialGames.length,feed.matches.length);assert.equal(reloaded.api.feedState.state,'unavailable');});
test('invalid stored JSON is ignored without deleting legacy manual records',()=>{for(const raw of ['{broken','{}']){const m=new Map([['j3-official-feed-v1',raw],['j3-elo-simulator-confirmed-v1','legacy']]);const t=tab(m);assert.equal(t.api.initialGames.length,90);assert.equal(m.get('j3-elo-simulator-confirmed-v1'),'legacy');}});
test('storage denied does not abort official application',()=>{const t=tab();t.ctx.localStorage.setItem=()=>{throw Error('quota')};assert.doesNotThrow(()=>t.api.applyOfficialFeed(feed));assert.equal(t.api.initialGames.length,feed.matches.length);});
test('older same-count feed cannot undo a score correction',()=>{const t=tab(),newer=structuredClone(feed);newer.updatedAt='2026-10-10T12:00:00Z';newer.matches.find(r=>r.game[0]==='奈良'&&r.game[1]==='北九州').game[2]=3;t.api.applyOfficialFeed(newer);const id=t.api.resultId();assert.throws(()=>t.api.applyOfficialFeed(feed),/Stale/);assert.equal(t.api.resultId(),id);});
test('invalid calendar dates, IDs, timestamps and unverified payloads cannot replace data',()=>{for(const change of [f=>f.verified=false,f=>f.asOfDate='2026-02-30',f=>f.updatedAt='bad',f=>f.matches[0].date='2026-08-32',f=>f.matches[0].id=f.matches[1].id,f=>f.matches[0].id='missing',f=>f.asOfDate='2026-10-11']){const t=tab(),bad=structuredClone(feed);change(bad);assert.throws(()=>t.api.applyOfficialFeed(bad));assert.equal(t.api.initialGames.length,90);}});
test('API timeout uses a separate live timeout for fallback',async()=>{let t;t=tab(new Map(),async(url,options)=>{if(url.includes('/api/')){t.timers.find(x=>x.ms===65000).f();assert(options.signal.aborted);throw Error('timeout');}assert(!options.signal.aborted);assert.equal(options.credentials,'omit');return {ok:true,json:async()=>feed};});await t.api.refreshOfficial();assert.equal(t.api.initialGames.length,feed.matches.length);assert.equal(t.api.feedState.refreshStatus,'fallback');assert.equal(t.api.feedState.officialCheckedAt,null);});
test('old fallback after API failure cannot regress newer saved scores',async()=>{const t=tab(new Map(),async url=>{if(url.includes('/api/'))throw Error('offline');return {ok:true,json:async()=>feed};}),newer=structuredClone(feed);newer.updatedAt='2026-10-10T12:00:00Z';newer.matches[0].game[2]++;t.api.applyOfficialFeed(newer);const id=t.api.resultId();await t.api.refreshOfficial();assert.equal(t.api.resultId(),id);assert.equal(t.api.feedState.state,'unavailable');});
test('another tab adopts only newer data and does not manufacture successful retrieval',()=>{const t=tab();t.api.applyOfficialFeed(feed);const newer=structuredClone(feed);newer.updatedAt='2026-10-10T12:00:00Z';newer.matches[0].game[2]++;t.storage.set(t.api.feedKey,JSON.stringify(newer));assert(t.api.restoreCachedFeed());assert.equal(t.api.feedState.state,'cached');assert.equal(t.api.initialGames[0][2],newer.matches[0].game[2]);t.storage.set(t.api.feedKey,JSON.stringify(feed));assert.equal(t.api.restoreCachedFeed(),false);});
