const fs=require('fs'),vm=require('vm'),assert=require('assert');
function harness(html,shared,initial={}){
 const map=new Map(Object.entries(initial)),els=new Map(),events={},timers=[];
 const el=id=>{if(!els.has(id))els.set(id,{value:id==='runs'?'10':'0',textContent:'',innerHTML:'',style:{},dataset:{},classList:{toggle(){},add(){},remove(){}},addEventListener(n,f){events[id+':'+n]=f},querySelectorAll:()=>[],close(){},showModal(){},click(){this.onclick?.()}});return els.get(id)};
 const ctx={localStorage:{getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},document:{hidden:false,getElementById:el,querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener:(n,f)=>events[n]=f,dispatchEvent(){}},Event:class{constructor(type){this.type=type}},confirm:()=>true,setTimeout:f=>timers.push(f),setInterval:f=>events.poll=f};ctx.window.localStorage=ctx.localStorage;
 vm.createContext(ctx);vm.runInContext(shared,ctx);ctx.J3Results=ctx.window.J3Results;
 vm.runInContext(html.match(/<script>\s*([\s\S]*?)<\/script>/)[1],ctx);
 return {map,els,ctx,events,eval:s=>vm.runInContext(s,ctx)};
}

const path=require('path'),root=path.resolve(process.argv[2]||path.join(__dirname,'..'));
const shared=fs.readFileSync(path.join(root,'shared-results.js'),'utf8'),main=fs.readFileSync(path.join(root,'index.html'),'utf8'),tracker=fs.readFileSync(path.join(root,'progress-tracker/index.html'),'utf8');
const KEY='j3-elo-simulator-confirmed-v1';let passed=0;
function check(name,fn){fn();passed++;console.log('PASS '+name)}
check('legacy manual mode and same-count wrong score never override official results',()=>{const saved={asofDate:'2026-10-04',played:9,points:13,wins:3,draws:4,losses:2,gf:12,ga:16};const initial={'giravanz-j3-progress-source-v1':'manual','giravanz-j3-progress-confirmed-v1':JSON.stringify(saved)};const h=harness(tracker,shared,initial);assert.equal(h.eval('activeStats.points'),10);assert.equal(h.eval('activeView'),'linked');assert.equal(h.map.get('giravanz-j3-progress-confirmed-v1'),JSON.stringify(saved));});
check('legacy actual rows and corrupt storage are ignored without deleting them',()=>{for(const raw of [JSON.stringify([['北九州','奈良',9,0]]),'{broken']){const initial={[KEY]:raw};const h=harness(main,shared,initial),t=harness(tracker,shared,initial);assert.equal(h.eval('confirmed().length'),90);assert.equal(t.eval('activeStats.played'),9);assert.equal(t.eval('activeStats.points'),10);assert.equal(h.map.get(KEY),raw);}});
check('tracker has no manual result controls and refresh button is touch sized',()=>{for(const id of ['confirm-main','save-confirm','main-fields','enable-sync'])assert(!tracker.includes('id="'+id+'"'));assert(tracker.includes('class="action secondary" id="refresh-official"'));});
check('90 unique matches, every club nine, Kitakyushu 10 points',()=>{const h=harness(main,shared);assert(h.eval('auditInitialData().ok'));assert.equal(h.eval('confirmed().length'),90);assert(h.eval('teams.every(c=>J3Results.clubStats(c).stats.played===9)'));assert.equal(h.eval('J3Results.clubStats().stats.points'),10);assert.equal(h.eval('remainingFixtures().length'),290)});
check('CSV reimport skips identical existing scores; conflicts and repeated cards rejected',()=>{const h=harness(main,shared);assert.equal(h.eval("parseRows('北九州,2,0,高知',380).add.length"),0);assert(h.eval("parseRows('北九州,9,0,高知',380).error.includes('異なります')"));assert(h.eval("parseRows('北九州,2,1,奈良\\n北九州,2,1,奈良',380).error"));assert(h.eval("parseRows('北九州,,1,奈良',380).error"))});
check('hypothetical matches excluded from tracker',()=>{const h=harness(main,shared);h.eval("scenarios.push(['北九州','奈良',3,0])");assert.equal(h.eval('stateWithScenario().pts[ix["北九州"]]'),13);assert.equal(h.eval('J3Results.clubStats().stats.points'),10)});
check('invalid and blank dates rejected while valid dates accepted',()=>{const h=harness(tracker,shared);assert.equal(h.eval('validate(defaults).length'),0);for(const date of ['', '2026-02-30','bad'])assert(h.eval('validate({...defaults,asofDate:'+JSON.stringify(date)+'}).length'));h.els.set('main-asofDate',{value:'2026-10-04'});for(const id of ['played','points','wins','draws','losses','gf','ga'])h.els.set('main-'+id,{value:''});assert(h.eval('validate(readStats("main")).length'))});
check('return from trial restores actual result even with unchanged saved signature',()=>{const h=harness(tracker,shared);h.eval("showResults({...activeStats,played:10,points:13,wins:3},'test')");h.events['show-main:click']();assert.equal(h.eval('activeStats.played'),9);assert.equal(h.eval('activeView'),'linked')});
check('complete season and impossible goals avoid NaN and negative remaining games',()=>{const h=harness(tracker,shared);h.eval("showResults({asofDate:'2027-01-01',played:38,points:114,wins:38,draws:0,losses:0,gf:100,ga:0},'test')");assert(!h.els.get('cards').innerHTML.includes('NaN'));h.eval("showResults({asofDate:'2027-01-01',played:38,points:0,wins:0,draws:0,losses:38,gf:0,ga:100},'test')");assert(!h.els.get('cards').innerHTML.includes('NaN'));assert(h.els.get('cards').innerHTML.includes('目標勝点に届かない'))});
check('simulation probabilities finite and consistently bounded',()=>{const h=harness(main,shared);const r=h.eval('simulate(20,[])');assert(r.every(x=>Number.isFinite(x.points)&&x.top2>=0&&x.top2<=x.top6&&x.top6<=100))});

const liveFeed=JSON.parse(fs.readFileSync(path.join(root,'official-results.json'),'utf8'));
const official={...liveFeed,asOfDate:'2026-10-04',matches:liveFeed.matches.filter(r=>r.date<='2026-10-04')};
check('latest published feed preserves all historical matches',()=>{const h=harness(main,shared);h.ctx.feed=liveFeed;h.eval('J3Results.applyOfficialFeed(feed);completed=J3Results.initialGames.map(g=>g.slice())');assert(h.eval('auditInitialData().ok'));assert.equal(h.eval('confirmed().length'),liveFeed.matches.length)});
check('official 90-match feed passes historical audit after chronological ordering',()=>{const h=harness(main,shared);h.ctx.feed=official;h.eval('J3Results.applyOfficialFeed(feed);completed=J3Results.initialGames.map(g=>g.slice())');assert(h.eval('auditInitialData().ok'));assert.equal(h.eval('confirmed().length'),official.matches.length)});
check('next official result updates tracker without manual registration',()=>{const h=harness(tracker,shared),f=JSON.parse(JSON.stringify(official));h.ctx.feed=f;h.eval('J3Results.applyOfficialFeed(feed);refreshLinkedResults()');const before=h.eval('({...activeStats})'),used=new Set(f.matches.map(r=>r.game[0]+'|'+r.game[1]));const opponent=h.eval('J3Results.initialGames.flatMap(g=>g.slice(0,2))').find(t=>t!=='北九州'&&!used.has(t+'|北九州'));if(!opponent)return;const date=new Date(f.asOfDate+'T00:00:00Z');date.setUTCDate(date.getUTCDate()+1);const iso=date.toISOString().slice(0,10);f.matches.push({id:iso.replaceAll('-','')+'01',date:iso,game:[opponent,'北九州',1,2]});f.asOfDate=iso;h.ctx.feed=f;h.eval('J3Results.applyOfficialFeed(feed);refreshLinkedResults()');assert.equal(h.eval('activeStats.played'),before.played+1);assert.equal(h.eval('activeStats.points'),before.points+3)});
check('official correction replaces score without increasing match count',()=>{const h=harness(tracker,shared),f=JSON.parse(JSON.stringify(official));h.ctx.feed=f;h.eval('J3Results.applyOfficialFeed(feed);refreshLinkedResults()');const before=h.eval('({...activeStats})'),row=f.matches.find(r=>r.game[0]==='北九州'&&r.game[1]==='高知'),delta=row.game[2]<30?1:-1;row.game[2]+=delta;h.ctx.feed=f;h.eval('J3Results.applyOfficialFeed(feed);refreshLinkedResults()');assert.equal(h.eval('activeStats.played'),before.played);assert.equal(h.eval('activeStats.gf'),before.gf+delta)});
check('invalid, duplicate, wrong-season and incomplete feeds rejected without losing existing results',()=>{for(const change of [f=>f.season='2025',f=>f.matches.pop(),f=>f.matches.push(f.matches[0]),f=>f.matches[0].game[2]=-1]){const h=harness(main,shared),f=JSON.parse(JSON.stringify(official));change(f);h.ctx.feed=f;assert.throws(()=>h.eval('J3Results.applyOfficialFeed(feed)'));assert.equal(h.eval('J3Results.clubStats().stats.played'),9)}});
check('verification requires successful retrieval, official values and actual mode',()=>{const h=harness(tracker,shared);assert.equal(h.eval('J3Results.verification(activeStats,true).ok'),false);h.ctx.feed=official;h.eval('J3Results.applyOfficialFeed(feed);refreshLinkedResults();renderVerification()');assert.equal(h.els.get('verification').dataset.verified,'true');h.eval("showResults({...activeStats},'test')");assert.equal(h.els.get('verification').dataset.verified,'false');h.eval("showResults({...activeStats},'main')");assert.equal(h.els.get('verification').dataset.verified,'false');});
check('same-count score correction changes ID and rejects stale display',()=>{const h=harness(tracker,shared);h.ctx.feed=JSON.parse(JSON.stringify(official));h.eval('J3Results.applyOfficialFeed(feed);refreshLinkedResults()');const id=h.eval('J3Results.resultId()');h.ctx.stale=h.eval('({...activeStats})');h.ctx.feed.matches.find(r=>r.game[0]==='北九州'&&r.game[1]==='高知').game[2]=3;h.eval('J3Results.applyOfficialFeed(feed)');assert.notEqual(h.eval('J3Results.resultId()'),id);assert.equal(h.eval('J3Results.verification(stale,true).ok'),false);h.eval('refreshLinkedResults()');assert.equal(h.eval('J3Results.verification(activeStats,true).ok'),true);});
console.log(passed+' regression checks passed');


